<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SettingMenuButton</name>
   <tag></tag>
   <elementGuidId>09b1afb6-621c-4331-9dd0-718d80bbf272</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#settings-menu-button</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
