<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TableListThreeDotButton</name>
   <tag></tag>
   <elementGuidId>86cd97c4-6086-46a6-94b5-09ba3020a283</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table/descendant::p[contains(text(),'${channelName}')]/following::button[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
