<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ContinueSignInButton</name>
   <tag></tag>
   <elementGuidId>98b1efba-bd66-42d9-b534-71c9db69e4b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>._button-login-id</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
