<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ContactTableHeader</name>
   <tag></tag>
   <elementGuidId>58d4d7d3-e3ac-4ac4-950d-cc8d7c57c881</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//thead/th</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
