name: Katalon CI/CD

on:
  push:
    branches:
      - master
      - ci-cd-integration
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  katalon:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'

    # Install required dependencies for running Chrome in headless mode
    - name: Install Chrome dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Install Katalon
      run: |
        curl -L -o katalon.tar.gz https://github.com/katalon-studio/katalon-studio/releases/download/v9.7.2/Katalon_Studio_Engine_Linux_64-9.7.2.tar.gz
        tar -xvzf katalon.tar.gz
        sudo mv Katalon_Studio_Engine_Linux_64-9.7.2 /opt/katalon

    # Set KATALON_HOME environment variable
    - name: Set KATALON_HOME
      run: echo "KATALON_HOME=/opt/katalon" >> $GITHUB_ENV

    - name: Run Katalon Test Suite
      run: |
        /opt/katalon/katalonc \
          -projectPath="$(pwd)/e2e-web.prj" \
          -retry=0 \
          -testSuitePath="Test Suites/Regression Web" \
          -executionProfile="CICD" \
          -browserType="Chrome" \
          -reportFolder="$(pwd)/report" \
          -apiKey="${{ secrets.KATALON_API_KEY }}" \
          --config -webui.autoUpdateDrivers=true \
          -Dwebdriver.chrome.options="--headless --no-sandbox --disable-dev-shm-usage --disable-gpu --remote-debugging-pipe"

    - name: Upload test reports
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: report/