name: Katalon CI

on:
  push:
    branches:
      - master
      - ci-cd-integration
  pull_request:
    branches:
      - master
  # Add the workflow_dispatch event to allow manual triggering
  workflow_dispatch:

jobs:
  katalon:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'adopt'

    - name: Install WebDriverManager
      run: |
        sudo apt-get install -y maven
        git clone https://github.com/bonigarcia/webdrivermanager.git
        cd webdrivermanager
        mvn clean package
    
    - name: Update ChromeDriver
      run: |
        CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
        DRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
        wget https://chromedriver.storage.googleapis.com/$DRIVER_VERSION/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /opt/katalonstudio/configuration/resources/drivers/chromedriver_linux64/chromedriver
        rm chromedriver_linux64.zip

    - name: Run Katalon in Docker
      run: |
        docker run -t --rm \
          -e JAVA_OPTS="-Djava.security.egd=file:/dev/./urandom -Duser.timezone=UTC" \
          -v ${{ github.workspace }}:/katalon/project \
          -v ${{ github.workspace }}/report:/katalon/report \
          katalonstudio/katalon:9-latest-slim katalonc \
          -projectPath="/katalon/project/e2e-web.prj" \
          -retry=0 \
          -testSuitePath="Test Suites/Regression Web" \
          -executionProfile="TestOps" \
          -browserType="Chrome" \
          -reportFolder="/katalon/report" \
          -apiKey="${{ secrets.KATALON_API_KEY }}" \
          --config -webui.autoUpdateDrivers=true \
          -Dwebdriver.chrome.options="--headless --no-sandbox --disable-dev-shm-usage --disable-gpu"