name: Katalon CI
on:
  push:
    branches:
      - master
      - ci-cd-integration
  pull_request:
    branches:
      - master
  # Add the workflow_dispatch event to allow manual triggering
  workflow_dispatch:
jobs:
  katalon-test:
    runs-on: self-hosted
    steps:
        # Step 1: Checkout the repository
        - name: Checkout repository
          uses: actions/checkout@v3

        # Step 2: Set up JDK (Katalon requires Java)
        - name: Set up JDK 8
          uses: actions/setup-java@v3
          with:
            java-version: 11

        # Step 3: Install Katalon Studio
        - name: Install Katalon Studio
          run: |
            wget https://github.com/katalon-studio/katalon-studio/releases/download/v8.4.0/Katalon_Studio_Linux_64-8.4.0.tar.gz
            tar -xzf Katalon_Studio_Linux_64-8.4.0.tar.gz

        # Step 4: Run Katalon Tests
        - name: Run Katalon Tests
          run: |
            ./katalonc -noSplash -runMode=console -projectPath="e2e-web.prj" -retry=0 -testSuitePath="Test Suites/Regression Web" -executionProfile="default" -browserType="Chrome"

        # Step 5: Store Test Results
        - name: Archive Test Results
          uses: actions/upload-artifact@v3
          with:
            name: test-results
            path: ./Reports/